from par_writer_runner import *

#execute_pip2(genlist=False)
#execute_lanl(genlist=True)
#execute_bebc(genlist=False)
#execute_lsnd(genlist=True)
execute_numi(genlist=False)
#execute_ship(genlist=False)
#execute_nucal(genlist=False)
#execute_charm(genlist=False)
#execute_bebc(genlist=False)
#execute_charm2(genlist=True)
#execute_miniboone_parallel(genlist=False)
#execute_t2k(genlist=True)
#execute_coherent(genlist=False)
#execute_seaquest(genlist=False)
